// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4a63b322f6e4d6110e3a3b9b7c67af306465e7e0/japanese-holidays/index.d.ts
declare module 'japanese-holidays' {
// Type definitions for japanese-holidays 1.0
// Project: https://github.com/osamutake/japanese-holidays-js
// Definitions by: syamatoo <https://github.com/syamatoo>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export function isHoliday(date: Date, furikae?: boolean): string | undefined;
export function isHolidayAt(date: Date, furikae?: boolean): string | undefined;
export function getHolidaysOf(year: number, furikae?: boolean): Holiday[];

export interface Holiday {
    month: number;
    date: number;
    name: string;
}
}
